#
# Changes to this file will be overwritten by `trmnlp pull`.
#
# Docs: https://help.usetrmnl.com/en/articles/10542599-importing-and-exporting-private-plugins#h_581fb988f0
#
---
strategy: polling
no_screen_padding: 'no'
dark_mode: 'no'
static_data: ''
polling_verb: get
polling_url: 'https://dev.to/api/articles?{% if tag and tag != "" %}tag={{ tag }}&{% endif %}{% if state == "top" %}top={{ top }}{% else %}state={{ state }}{% endif %}'
polling_headers: ''
name: Dev.to Articles
refresh_interval: 360
settings:
  - name: tag
    type: text
    label: 'Tag'
    description: 'Filter articles by tag (e.g., javascript, python)'
    required: false
  - name: state
    type: select
    label: 'Filter'
    description: 'Filter by article state or popularity'
    required: false
    options:
      - label: 'Fresh'
        value: 'fresh'
      - label: 'Rising'
        value: 'rising'
      - label: 'All'
        value: 'all'
      - label: 'Top (Most Popular)'
        value: 'top'
    default: fresh
    conditional_validation:
      - when: top
        hidden:
          - state_hidden
      - when: fresh
        hidden:
          - top
      - when: rising
        hidden:
          - top
      - when: all
        hidden:
          - top
  - name: top
    type: select
    label: 'Time Period'
    description: 'Show most popular articles from selected time period'
    required: false
    optional: true
    options:
      - label: 'Today'
        value: '1'
      - label: 'Last 7 Days'
        value: '7'
      - label: 'Last 30 Days'
        value: '30'
      - label: 'Last 6 Months'
        value: '180'
      - label: 'Last Year'
        value: '365'
      - label: 'All Time'
        value: '9999'
    default: '7'
  - name: show_thumbnail
    type: boolean
    label: 'Show Thumbnails'
    description: 'Display article cover images as thumbnails'
    required: false
    default: false
